blue:
  hmax: 290
  hmin: 150
green:
  hmax: 160
  hmin: 80
image:
  ROI_height: 480
  ROI_wdith: 640
  ROI_x: 0
  ROI_y: 0
  reg_x:
    K1: -0.000466202886512304
    B1: 0.3213944554044232
  reg_y:
    K2: -0.0005177692640623248
    B2: 0.1515581167946396
red:
  hmax: 30
  hmin: 0
yellow:
  hmax: 70
  hmin: 50
