blue:
  hmax: 360
  hmin: 130
green:
  hmax: 200
  hmin: 70
image:
  ROI_height: 480
  ROI_wdith: 640
  ROI_x: 0
  ROI_y: 0
  reg_x:
  - -0.0007163415414134951
  - 0.3942085065558042
  reg_y:
  - -0.0007835257782613274
  - 0.24239374583230974
red:
  hmax: 30
  hmin: 0
